### ISSUE TITLE
Install HiCPlus

### ISSUE THREAD

**Issue by ghost** [wangjuan001/hicplus#13]
I am attempting to install HiCPlus by following the steps outlined in the tutorial :

conda config --add channels pytorch  
conda create -n plus python=3.6 numpy pytorch torchvision scipy
python3 -m pip install hic-straw  
source activate plus  
git clone https://github.com/wangjuan001/hicplus.git  
cd hicplus
python setup.py install  

After this, I tried running the command : 

hicplus -h

I received the following error :

Traceback (most recent call last):
  File "/home/miniconda3/envs/plus/bin/hicplus", line 4, in <module>
    __import__('pkg_resources').run_script('hicplus==1.1.0', 'hicplus')
  File "/home/miniconda3/envs/plus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/miniconda3/envs/plus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/miniconda3/envs/plus/lib/python3.6/site-packages/hicplus-1.1.0-py3.6.egg/EGG-INFO/scripts/hicplus", line 3, in <module>
    from hicplus import pred_chromosome, train_models, pred_genome
  File "/home/miniconda3/envs/plus/lib/python3.6/site-packages/hicplus-1.1.0-py3.6.egg/hicplus/pred_chromosome.py", line 8, in <module>
    import straw
ModuleNotFoundError: No module named 'straw'

Even though I tried manually adding " import straw " in pred_chromosome.py, I continue to encounter the same error.

**Comment by gotouerina** [comment]
I guess it is beacause hic-straw has updated and remove straw.py...
Maybe download an old package is useful.
