### ISSUE TITLE
HiCPlus Trial doesn't work

### ISSUE THREAD

**Issue by papelypluma** [wangjuan001/hicplus#8]
Hi HiCPlus developers, 

Installation went fine with no errors, but running the trial/test on training throws out an error. 

> 0:00:00.000006
> Traceback (most recent call last):
>   File "/home/datb/miniconda3/envs/hicplus/bin/hicplus", line 4, in <module>
>     __import__('pkg_resources').run_script('hicplus==1.1.0', 'hicplus')
>   File "/home/datb/miniconda3/envs/hicplus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 651, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/home/datb/miniconda3/envs/hicplus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1448, in run_script
>     exec(code, namespace, namespace)
>   File "/home/datb/miniconda3/envs/hicplus/lib/python3.6/site-packages/hicplus-1.1.0-py3.6.egg/EGG-INFO/scripts/hicplus", line 89, in <module>
>     run()
>   File "/home/datb/miniconda3/envs/hicplus/lib/python3.6/site-packages/hicplus-1.1.0-py3.6.egg/EGG-INFO/scripts/hicplus", line 85, in run
>     args.func(args)
>   File "/home/datb/miniconda3/envs/hicplus/lib/python3.6/site-packages/hicplus-1.1.0-py3.6.egg/hicplus/train_models.py", line 23, in main
>     highres = utils.train_matrix_extract(args.chromosome, 10000, args.inputfile)
>   File "/home/datb/miniconda3/envs/hicplus/lib/python3.6/site-packages/hicplus-1.1.0-py3.6.egg/hicplus/utils.py", line 104, in train_matrix_extract
>     result = straw.straw('NONE', hicfile, str(chrN1),str(chrN1),'BP',binsize)
> TypeError: straw(): incompatible function arguments. The following argument types are supported:
>     1. (arg0: str, arg1: str, arg2: str, arg3: str, arg4: str, arg5: str, arg6: int) -> List[contactRecord]
> 
> Invoked with: 'NONE', 'https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/combined.hic', '19', '19', 'BP', 10000

Any help is very much appreciated. Thank you.

**Comment by papelypluma** [comment]
I tried installing a previous version of straw (https://pypi.org/project/hic-straw/0.0.6/), and it appeared to address the issue. At the time of this writing, hic-straw is at v1.0.0.1.
